# Generated by Django 2.2.5 on 2019-09-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
