# Generated by Django 2.2.1 on 2019-09-12 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

        ('resources', '0002_auto_20190911_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
