# Generated by Django 2.2.5 on 2019-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190911_1532'),
        ('resources', '0002_auto_20190911_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
