# Generated by Django 2.2.5 on 2019-09-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='students',
        ),
    ]
