# Generated by Django 2.2.1 on 2019-09-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_resource_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='resource',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
