# Generated by Django 2.2.1 on 2019-09-12 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20190912_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='students',
            field=models.ManyToManyField(related_name='resource_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
