# Generated by Django 2.2.1 on 2019-09-12 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_auto_20190912_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='students',
        ),
        migrations.AddField(
            model_name='resource',
            name='courses',
            field=models.ManyToManyField(related_name='resource_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
