# Generated by Django 2.2.1 on 2019-09-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20190912_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='courses',
            field=models.ManyToManyField(related_name='resource_courses', to='courses.Course'),
        ),
    ]
